name: 'Send EMail with AWS SES'
description: 'Sending Email via Amazon Simple Email Service'
branding:
  icon: 'info'
  color: 'orange'
inputs:
  smtp-server:
    description: 'The smtp server to use'
    required: true
  smtp-port:
    description: 'The smtp port to use'
    required: false
    default: '465'
  smtp-secure:
    description: 'If the smtp server uses ssl'
    required: false
    default: 'true'
  from-email:
    description: 'The sender of the mail'
    required: true
  to-email:
    description: 'The recipients of the mail seperated by comma'
    required: true
  username:
    description: 'The username of the mail account'
    required: true
  password:
    description: 'The password of the mail account'
    required: true
  subject:
    description: 'The subject of the mail'
    required: true
  body:
    description: 'The body of the mail'
  html:
    description: 'If the mail is html'

runs:
  using: 'node20'
  main: 'dist/index.js'
